language: python

dist: trusty

matrix:
  fast_finish: true
  include:

# linux + python

    - os: linux
      python: 2.6
      name: ubuntu 14.04 - python@2.6
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 2.7
      name: ubuntu 14.04 - python@2.7
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.3
      name: ubuntu 14.04 - python@3.3
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.4
      name: ubuntu 14.04 - python@3.4
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.5
      name: ubuntu 14.04 - python@3.5
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 14.04 - python@3.6
      sudo: true
      env:
        - MATRIX_EVAL=""

  allow_failures:
    - name: ubuntu 14.04 - python@2.6


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  #- pip install -r requirements.txt
  - pip install Pillow
  - pip install opencv-python
  - pip install matplotlib
  - pip install pytest
  - pip install enum34

install:
  - python setup.py install

script:
  - exit 0
#  - pytest
