clone_folder: c:\projects\NumPyNet

environment:

  WORKSPACE: C:\projects

  matrix:

  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
  - python --version
  - cd %WORKSPACE%\NumPyNet
  - pip install -r requirements.txt
  - python setup.py install

#test_script:
#  - pytest
