site_name:          NumPyNet
repo_url:           https://github.com/Nico-Curti/NumPyNet
site_description:   Neural Networks in Pure NumPy
site_author:        https://www.unibo.it/sitoweb/nico.curti2

extra_css:          assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Nico-Curti'
    - type: 'Unibo'
      link: 'https://www.unibo.it/sitoweb/nico.curti2'

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys

  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - install.md
  - authors.md
  - NumPyNet.md
  - NumPyNet/layers/activation_layer.md
  - NumPyNet/layers/avgpool_layer.md
  - NumPyNet/layers/batchnorm_layer.md
  - NumPyNet/layers/connected_layer.md
  - NumPyNet/layers/convolutional_layer.md
  - NumPyNet/layers/cost_layer.md
  - NumPyNet/layers/dropout_layer.md
  - NumPyNet/layers/input_layer.md
  - NumPyNet/layers/l1norm_layer.md
  - NumPyNet/layers/l2norm_layer.md
  - NumPyNet/layers/logistic_layer.md
  - NumPyNet/layers/maxpool_layer.md
  - NumPyNet/layers/pixelshuffle_layer.md
  - NumPyNet/layers/route_layer.md
  - NumPyNet/layers/shortcut_layer.md
  - NumPyNet/layers/upsample_layer.md
  - NumPyNet/layers/yolo_layer.md

theme:
  - jekyll-theme-slate
